using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//namespace ExamenLogica2
//{
//    internal class F11
//    {
//        public static string F(string str)
//        {
//            try
//            {
//                Console.Write("1");
//                int.Parse(str);
//                Console.Write("2");
//                return "A";
//            }
//            catch (Exception)
//            {
//                Console.Write("4");
//                return "C";
//            }
//            Console.Write("3");
//            return "B";
//        }

//        public static void Main()
//        {
//            Console.Write(F("C"));
//        }

//        //Respuesta: entra en el try, coge el 1, y como hace la conversion salta al exception, tomando
//        //los valores de 4 y c del return
//        //Solucion: 14C
//    }
//}
